name = "portfolio"

main = "./dist/_worker.js/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-06-22"

routes = [
    { pattern = "jarodg.dev", custom_domain = true },
    { pattern = "www.jarodg.dev", custom_domain = true }
]

[assets]
binding = "ASSETS"
directory = "./dist"

[vars]
NODE_VERSION = "24"

[observability]
enabled = true