name: Deploy to AWS

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
            - uses: aws-actions/setup-sam@v2
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-west-2
            # sam build
            - run: sam build --use-container --build-image amazon/aws-sam-cli-build-image-python3.12

            # Run Unit tests- Specify unit tests here

            # sam deploy
            - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-diagnostic-emailer --s3-bucket sam-deploy-jpg-portfolio --capabilities CAPABILITY_IAM --region us-west-2
